"""Hard safety bounds for the TradingLabs Pine-compatible subset."""

from __future__ import annotations

MAX_SOURCE_CHARS = 30_000
MAX_AST_NODES = 2_000
MAX_EXPRESSION_DEPTH = 32
MAX_LOOKBACK = 2_000
MAX_SECURITY_CALLS = 5
MAX_PLOTS = 30
MAX_INPUTS = 20
MAX_STATEMENTS = 200
MAX_BARS = 2_500
MAX_OPERATION_COST = 2_000_000
HISTORY_BUFFER_BARS = 300
SCAN_CONCURRENCY = 8
SCAN_RATE_LIMIT_PER_MINUTE = 5
LANGUAGE_MODE = "pine_subset_v1"
SUPPORTED_VERSIONS = {5, 6}
SUPPORTED_TIMEFRAMES = {"1D", "D", "1d", "daily"}
DISPLAY_TIMEFRAME = "1D"
DEFAULT_UNIVERSE_ID = "nse-755"
DEFAULT_UNIVERSE_LABEL = "755 Stocks"
